LoadPackage("qpa");
Read("../Functions.g");

# Creating the quiver
Q := Quiver(4, [[1, 2, "a"], [2, 4, "b"], [1, 3, "c"], [3, 4, "d"]]); 
# Creating a PathAlgebra from the quiver
pa := PathAlgebra(Rationals, Q); 

# We let I := principal ideal generated by the relations
relations := [pa.a * pa.b - pa.c * pa.d];

# This is the quotient of pa and I
quot := pa / relations;

AssignGeneratorVariables(quot);

IsFractionalCalabiYau(pa, 20);
